### PR TITLE
Add "Assembly Round 3" staking result

### PR DESCRIPTION
**Pull request by dlt-green**
We want to verify the outcome of the `Assembly Round 3` staking event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

* Copy the following bash script into a file called `participation_get_result_assembly_03.sh`

```shell
#!/bin/bash
ADDR="http://YOUR-NODE-ADDRESS:14265"
TOKEN="YOUR-JWT-TOKEN"

EVENT_ID="79958d5ccaaa81cea1dc8b589655d369b16c72f27a44433ba22c5b0a7dc89356"
RESULT_FILE="assembly_03.json"

EVENT_STATUS="$( curl ${ADDR}/api/plugins/participation/events/${EVENT_ID}/status \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data.status' )"

grep -q 'ended' <<< "${EVENT_STATUS}" || { echo "ERROR: event has not ended yet"; exit 1 ; }

curl ${ADDR}/api/plugins/participation/admin/events/${EVENT_ID}/rewards \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data' ${RESULT_FILE}

printf "Symbol:          %s\n" "$(jq '.symbol' ${RESULT_FILE})"
printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${RESULT_FILE})"
printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${RESULT_FILE})"
printf "Checksum:        %s\n" "$(jq '.checksum' ${RESULT_FILE})"
```

* Replace `ADDR` with the public REST API address of your HORNET node.
* Replace `TOKEN` with your JWT Token. You can create a token using `./hornet tool jwt-api`.
* Save the file.
* Run `sudo apt update && sudo apt install curl jq`
* Run `chmod +x participation_get_result_assembly_03.sh`
* Run `./participation_get_result_assembly_03.sh`
* Copy the output of the script as a comment to this PR.
* Please press "Approve" if your checksum matches `53b00a41a8fe0c217a59ff8fe940b9af87cc877647e042db78c9b11f8edc908f`.
  grafik

### CODE REVIEW

**Review by dlt-green — COMMENTED** [review]
image

**Review by fhb191309 — APPROVED** [review]
asmb-event-03

**Comment by bogenlos** [comment]
Screenshot_20221027-173801_JuiceSSH

**Review by bogenlos — APPROVED** [review]

**Review by ockerocker — APPROVED** [review]
Bildschirmfoto vom 2022-10-27 17-51-24

**Comment by shufps** [comment]
matches on all of our nodes:
```
Symbol:          "microASMB"
Milestone index: 4717923
Total rewards:   1043645148374044
Checksum:        "53b00a41a8fe0c217a59ff8fe940b9af87cc877647e042db78c9b11f8edc908f"

```

**Comment by Sn00pyoo7** [comment]
Symbol:          "microASMB"
Milestone index: 4717923
Total rewards:   1043645148374044
Checksum:        "53b00a41a8fe0c217a59ff8fe940b9af87cc877647e042db78c9b11f8edc908f"

**Review by the-real-rapete — APPROVED** [review]
Event ID: "79958d5ccaaa81cea1dc8b589655d369b16c72f27a44433ba22c5b0a7dc89356"
Symbol: "microASMB"  
Milestone index: 4717923
Total rewards:   1043645148374044
Checksum: "53b00a41a8fe0c217a59ff8fe940b9af87cc877647e042db78c9b11f8edc908f"

**Comment by DerAnhalter** [comment]
I get this :-(

Assembly_R3_SR

**Review by DerAnhalter — APPROVED** [review]

**Comment by jkl2e** [comment]
Bildschirm­foto 2022-10-28 um 08 22 15

**Comment by vromvonbeyond** [comment]
image

**Review by vromvonbeyond — APPROVED** [review]

**Comment by mogulbuster** [comment]
Screenshot 2022-10-28 at 10 22 07

**Comment by muXxer** [comment]
```
Symbol:          "microASMB"
Milestone index: 4717923
Total rewards:   1043645148374044
Checksum:        "53b00a41a8fe0c217a59ff8fe940b9af87cc877647e042db78c9b11f8edc908f"
```
@dlt-green thx for creating that PR! Thats how it should be :heart:

**Review by muXxer — APPROVED** [review]

**Comment by martinDSC10** [comment]
event3_approval

**Review by martinDSC10 — APPROVED** [review]

**Review by p00dl — APPROVED** [review]
image

**Comment by TimsonLabs** [comment]
Assembly Round 3 - Staking Result

**Comment by TimsonLabs** [comment]
Assembly Round 3 - Staking Result

**Review by TimsonLabs — APPROVED** [review]

**Review by gobbli — APPROVED** [review]
image

**Review by zKtota — APPROVED** [review]
image

**Comment by arniMUC** [comment]
FFA19129-4DFA-4D1C-A708-CF855513A40D

Habe es am Montag erledigt sollte eigentlich auch passen oder?

**Pull request merged**
