### PR TITLE
Add "Assembly Round 4" staking result

### PR DESCRIPTION
**Pull request by dlt-green**
We want to verify the outcome of the `Assembly Round 4` staking event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

* Copy the following bash script into a file called `participation_get_result_assembly_04.sh`

```shell
#!/bin/bash
ADDR="http://YOUR-NODE-ADDRESS:14265"
TOKEN="YOUR-JWT-TOKEN"

EVENT_ID="758f9f6193c4ecc99b4b3c1a57a9cd3c6fc75f94e061d05361647d11ab8d06f6"
RESULT_FILE="assembly_04.json"

EVENT_STATUS="$( curl ${ADDR}/api/plugins/participation/events/${EVENT_ID}/status \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data.status' )"

grep -q 'ended' <<< "${EVENT_STATUS}" || { echo "ERROR: event has not ended yet"; exit 1 ; }

curl ${ADDR}/api/plugins/participation/admin/events/${EVENT_ID}/rewards \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data' ${RESULT_FILE}

printf "Symbol:          %s\n" "$(jq '.symbol' ${RESULT_FILE})"
printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${RESULT_FILE})"
printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${RESULT_FILE})"
printf "Checksum:        %s\n" "$(jq '.checksum' ${RESULT_FILE})"
```

* Replace `ADDR` with the public REST API address of your HORNET node.
* Replace `TOKEN` with your JWT Token. You can create a token using `./hornet tool jwt-api`.
* Save the file.
* Run `sudo apt update && sudo apt install curl jq`
* Run `chmod +x participation_get_result_assembly_04.sh`
* Run `./participation_get_result_assembly_04.sh`
* Copy the output of the script as a comment to this PR.
* Please press "Approve" if your checksum matches `1f5641ea80898125ce877b97aec0db868fc5307284078fdc61aa17d9327cebaf`.
  grafik

### CODE REVIEW

**Comment by dlt-green** [comment]
image

**Review by fhb191309 — APPROVED** [review]
asmb_round_4

**Review by ockerocker — APPROVED** [review]
Bildschirmfoto vom 2023-02-05 19-28-51

**Comment by vromvonbeyond** [comment]
image

**Review by vromvonbeyond — APPROVED** [review]

**Comment by Tombaaa** [comment]
image
verified

**Comment by uknawn** [comment]
image

**Review by Tombaaa — COMMENTED** [review]
reviewed / checked / confirmed / approved

**Review by Tombaaa — APPROVED** [review]

**Review by uknawn — APPROVED** [review]

**Review by no8ody — APPROVED** [review]

**Comment by bogenlos** [comment]
image

**Review by bogenlos — APPROVED** [review]

**Review by p00dl — APPROVED** [review]
image

**Comment by Travetown** [comment]
Bildschirm­foto 2023-02-05 um 21 37 23

**Review by mag-node — APPROVED** [review]
Assembly Round 4-Die_Zweite

**Review by Travetown — APPROVED** [review]

**Review by 0xKtota — APPROVED** [review]
image

**Comment by TimsonLabs** [comment]
ASMB

**Review by TimsonLabs — APPROVED** [review]

**Comment by 2g4y1** [comment]
Screenshot_20230206-074315

**Review by 2g4y1 — APPROVED** [review]

**Comment by shufps** [comment]
we have the same :blush: 
```
Symbol:          "microASMB"
Milestone index: 5590887
Total rewards:   1208230692999165
Checksum:        "1f5641ea80898125ce877b97aec0db868fc5307284078fdc61aa17d9327cebaf"
```

**Review by martinDSC10 — APPROVED** [review]
assembly_4

**Review by creps — APPROVED** [review]
image

**Review by muXxer — APPROVED** [review]

**Review by DerAnhalter — APPROVED** [review]
Symbol:          "microASMB"
Milestone index: 5590887
Total rewards:   1208230692999165
Checksum: "1f5641ea80898125ce877b97aec0db868fc5307284078fdc61aa17d9327cebaf"

**Comment by Sn00pyoo7** [comment]
Unbenannt

**Review by Sn00pyoo7 — APPROVED** [review]

**Comment by Danlino** [comment]
Symbol:          "microASMB"
Milestone index: 5590887
Total rewards:   1208230692999165
Checksum:        "1f5641ea80898125ce877b97aec0db868fc5307284078fdc61aa17d9327cebaf"

**Review by OMSKremer — APPROVED** [review]
Symbol: "microASMB"
Milestone index: 5590887
Total rewards: 1208230692999165
Checksum: "1f5641ea80898125ce877b97aec0db868fc5307284078fdc61aa17d9327cebaf"

**Review by Schnurzle — APPROVED** [review]
Symbol:          "microASMB"
Milestone index: 5590887
Total rewards:   1208230692999165
Checksum:        "1f5641ea80898125ce877b97aec0db868fc5307284078fdc61aa17d9327cebaf"

**Review by Danlino — APPROVED** [review]

**Comment by hackicodi** [comment]
Symbol: "microASMB"
Milestone index: 5590887
Total rewards: 1208230692999165
Checksum: "1f5641ea80898125ce877b97aec0db868fc5307284078fdc61aa17d9327cebaf"


Press any key to continue

**Review by DrWoyzeck — COMMENTED** [review]
image

**Comment by sowhat-git** [comment]
image

**Pull request merged**
