### PR TITLE
Verify "Assembly Staking Round 6" result

### PR DESCRIPTION
**Pull request by no8ody**
We want to verify the outcome of the `Assembly Round 6` staking event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

Copy the following bash script into a file called `participation_get_result_assembly_06.sh`
```bash
#!/bin/bash
ADDR="https://YOUR-NODE-ADDRESS"
TOKEN="YOUR-JWT-TOKEN"

EVENT_ID="a0e2605db376b5236961e0b05c753700fc8d6b061bd4564289fcfda936bcd59b"
RESULT_FILE="assembly_06.json"

EVENT_STATUS="$( curl ${ADDR}/api/plugins/participation/events/${EVENT_ID}/status \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data.status' )"

grep -q 'ended' <<< "${EVENT_STATUS}" || { echo "ERROR: event has not ended yet"; exit 1 ; }

curl ${ADDR}/api/plugins/participation/admin/events/${EVENT_ID}/rewards \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data' > ${RESULT_FILE}

printf "Symbol:          %s\n" "$(jq '.symbol' ${RESULT_FILE})"
printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${RESULT_FILE})"
printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${RESULT_FILE})"
printf "Checksum:        %s\n" "$(jq '.checksum' ${RESULT_FILE})"
```
* Replace `ADDR` with the public REST API address of your HORNET node.
* Replace `TOKEN` with your JWT Token. You can create a token using `./hornet tool jwt-api`.
* Save the file.
* Run `sudo apt update && sudo apt install curl jq`
* Run `chmod +x participation_get_result_assembly_06.sh`
* Run `./participation_get_result_assembly_06.sh`
* Copy the output of the script as a comment to this PR.
* Please press "Approve" if your checksum matches `94bdc2f27d07bf0becf5e4167faf1503c95ca6514b11e828b7f746f6fba99548`.

160444960-ccf6dedf-df57-4949-9828-131285c66848

### CODE REVIEW

**Comment by bogenlos** [comment]
Screenshot_20230817-170254_JuiceSSH

**Review by bogenlos — APPROVED** [review]

**Review by ockerocker — APPROVED** [review]
Bildschirmfoto vom 2023-08-17 15-46-29

**Comment by JannemanDev** [comment]
IMG_1312

**Review by JannemanDev — APPROVED** [review]

**Review by DerAnhalter — APPROVED** [review]
/var/lib/hornet $ sudo ./participation_get_result_assembly_06.sh 
Symbol:          "microASMB"
Milestone index: 7257868
Total rewards:   940150712123561
Checksum:        "94bdc2f27d07bf0becf5e4167faf1503c95ca6514b11e828b7f746f6fba99548"

**Review by AlexTweeet — COMMENTED** [review]
Bildschirmfoto 2023-08-18 um 10 06 48

**Review by Danlino — APPROVED** [review]
R6

**Review by mag-node — APPROVED** [review]
Assambly_6

**Comment by Konjunktiv** [comment]
Bildschirmfoto vom 2023-08-18 21-23-22

**Review by Konjunktiv — APPROVED** [review]

**Comment by Sn00pyoo7** [comment]
wauwau

**Comment by Sn00pyoo7** [comment]
wauwau

**Review by Sn00pyoo7 — APPROVED** [review]

**Review by dlt-green — APPROVED** [review]
image

**Review by DrWoyzeck — APPROVED** [review]
Found6

**Review by martinDSC10 — APPROVED** [review]
image

**Review by TimsonLabs — APPROVED** [review]
ASMB Staking Round 6

**Review by 2g4y1 — APPROVED** [review]
Screenshot_20230821-075610

**Review by Tombaaa — APPROVED** [review]
image

**Review by vromvonbeyond — APPROVED** [review]
image

vrom approved!

**Review by OMSKremer — APPROVED** [review]
$ sh participation_get_result_assembly_06.sh
 Symbol: "microASMB"
 Milestone index: 7257868
 Total rewards: 940150712123561
 Checksum: "94bdc2f27d07bf0becf5e4167faf1503c95ca6514b11e828b7f746f6fba99548"

**Comment by shufps** [comment]
We have
```
Symbol:          "microASMB"
Milestone index: 7257868
Total rewards:   940150712123561
Checksum:        "94bdc2f27d07bf0becf5e4167faf1503c95ca6514b11e828b7f746f6fba99548"
```
on all of our api nodes :ok_hand:

**Comment by alexsporn** [comment]
Thanks @no8ody

**Review by 0xKtota — COMMENTED** [review]
Approved
Symbol:          "microASMB"
Milestone index: 7257868
Total rewards:   940150712123561
Checksum:        "94bdc2f27d07bf0becf5e4167faf1503c95ca6514b11e828b7f746f6fba99548"

**Pull request merged**
