### PR TITLE
Verify "Shimmer Ecosystem Funding Proposal" result

### PR DESCRIPTION
**Pull request by fhb191309**
We want to verify the outcome of the `Shimmer Ecosystem Funding Proposal` event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

 - Open a new tab in your browser and go to `http://YOUR-NODE- ADDRESS:14265/api/plugins/participation/events/9e8e1a15c831441797912a86022f5a78fcb70e151e43fe84812d4c7f6eb79a7b/status` 
(YOUR-NODE-ADDRESS should really be your own node, otherwise we all compare results from the same nodes)

 - Check that the status of the event is "ended"

 - Please press "Approve" if your checksum matches 7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c.
 
 According to the last Governance Results Verification: https://github.com/iotaledger/participation-events/pull/6

### CODE REVIEW

**Review by dlt-green — APPROVED** [review]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Comment by MyMonk089** [comment]
Bildschirm­foto 2022-08-01 um 21 42 22

**Comment by muXxer** [comment]
Can you please rename the file to `shimmer_funding.json`.

**Comment by DerAnhalter** [comment]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Comment by zKtota** [comment]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Comment by fhb191309** [comment]
> Can you please rename the file to `shimmer_funding.json`, so it fits the participation event definition file name.

Done

**Review by muXxer — APPROVED** [review]

**Comment by vromvonbeyond** [comment]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Review by zKtota — APPROVED** [review]

**Comment by DrWoyzeck** [comment]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Comment by MyMonk089** [comment]
Please everyone who has the same results on his node do this approvement, too. 

Bildschirm­foto 2022-08-01 um 21 53 56

**Review by DerAnhalter — APPROVED** [review]

**Review by vromvonbeyond — APPROVED** [review]

**Review by stowoxla — APPROVED** [review]

**Review by DrWoyzeck — APPROVED** [review]

**Review by MiKeF05 — APPROVED** [review]

**Review by creps — APPROVED** [review]

**Review by o-l-i-v-e-r — APPROVED** [review]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}
image

**Review by SpeedyNo1 — APPROVED** [review]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Comment by gobbli** [comment]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Review by ockerocker — APPROVED** [review]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Review by alexsporn — APPROVED** [review]

**Review by p00dl — APPROVED** [review]
image

**Comment by mogulbuster** [comment]
Shimmer Ecosystem Funding Proposal, checksums verified through SWARM

**Comment by arniMUC** [comment]
wie kann ich hier  bitte Teilnehmer werden um mit meiner Node "https://maxx.dlt.green14265/api/plugins/participation/events/9e8e1a15c831441797912a86022f5a78fcb70e151e43fe84812d4c7f6eb79a7b/status"  an der Abstimmung teilzunehmen ?

**Review by bogenlos — APPROVED** [review]
{"data":{"milestoneIndex":3931323,"status":"ended","questions":[{"answers":[{"value":1,"current":165717923542,"accumulated":8016019115490064},{"value":2,"current":217119840496,"accumulated":6788243478652862},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"}}

**Comment by MyMonk089** [comment]
> wie kann ich hier bitte Teilnehmer werden um mit meiner Node "https://maxx.dlt.green14265/api/plugins/participation/events/9e8e1a15c831441797912a86022f5a78fcb70e151e43fe84812d4c7f6eb79a7b/status" an der Abstimmung teilzunehmen ?

Hast du denn mit deiner Node das Voting aufgezeichnet, also im Participation Plugin das Event eingetragen gehabt bevor das Event begann?

**Comment by TeeVeeEss** [comment]
```
curl http://localhost:14265/api/plugins/participation/events/9e8e1a15c831441797912a86022f5a78fcb70e151e43fe84812d4c7f6eb79a7b/status |jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   373  100   373    0     0   182k      0 --:--:-- --:--:-- --:--:--  182k
{
  "data": {
    "milestoneIndex": 3931323,
    "status": "ended",
    "questions": [
      {
        "answers": [
          {
            "value": 1,
            "current": 165717923542,
            "accumulated": 8016019115490064
          },
          {
            "value": 2,
            "current": 217119840496,
            "accumulated": 6788243478652862
          },
          {
            "value": 0,
            "current": 0,
            "accumulated": 0
          },
          {
            "value": 255,
            "current": 0,
            "accumulated": 0
          }
        ]
      }
    ],
    "checksum": "7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"
  }
}
```

**Review by TeeVeeEss — APPROVED** [review]

**Comment by Dr-Electron** [comment]
```
{
  "data": {
    "milestoneIndex": 3931323,
    "status": "ended",
    "questions": [
      {
        "answers": [
          {
            "value": 1,
            "current": 165717923542,
            "accumulated": 8016019115490064
          },
          {
            "value": 2,
            "current": 217119840496,
            "accumulated": 6788243478652862
          },
          {
            "value": 0,
            "current": 0,
            "accumulated": 0
          },
          {
            "value": 255,
            "current": 0,
            "accumulated": 0
          }
        ]
      }
    ],
    "checksum": "7b3631e309dc3287a8cc3251eb9c5b08566cf76f861b80948b02d616b532233c"
  }
}
```

**Review by Dr-Electron — APPROVED** [review]

**Comment by fhb191309** [comment]
can merge this pull request?

**Pull request merged**
