### PR TITLE
Verify "IOTA Community Governance Vote" result

### PR DESCRIPTION
**Pull request by muXxer**
We want to verify the outcome of the `IOTA Community Governance Vote` event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:
- Open a new tab in your browser and go to `http://YOUR-NODE-ADDRESS:14265/api/plugins/participation/events/c8529ff64ea191b437cd625af8b02fd0173bc94aae380ea4cc3367a651536cba/status` (YOUR-NODE-ADDRESS should really be your own node, otherwise we all compare results from the same nodes)
- Check that the `status` of the event is `"ended"`
- Please press "Approve" if your `checksum` matches `9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6`. 
grafik

### CODE REVIEW

**Review by dlt-green — APPROVED** [review]

**Review by MyMonk089 — APPROVED** [review]

**Review by fhb191309 — APPROVED** [review]

**Review by Masoholik — APPROVED** [review]

**Review by Fredericvn — APPROVED** [review]

**Review by Sn00pyoo7 — APPROVED** [review]

**Review by MiKeF05 — APPROVED** [review]

**Review by DerAnhalter — APPROVED** [review]

**Review by gobbli — APPROVED** [review]

**Review by fhb191309 — COMMENTED** [review]
`{"data":{"milestoneIndex":3542544,"status":"ended","questions":[{"answers":[{"value":1,"current":372250343375,"accumulated":30820033631800549},{"value":2,"current":74402847655,"accumulated":6414706069859334},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6"}}`

**Review by OMSKremer — APPROVED** [review]

**Review by Arion941 — APPROVED** [review]

**Review by Snowli11 — APPROVED** [review]

**Review by jeliasson — APPROVED** [review]

**Review by uknawn — APPROVED** [review]

**Review by uwec — APPROVED** [review]
Ckecksum verified at 3 nodes.
"checksum": "9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6"

**Review by baylander — APPROVED** [review]
https://myiotanode.eu/api/plugins/participation/events/c8529ff64ea191b437cd625af8b02fd0173bc94aae380ea4cc3367a651536cba/status

{"data":{"milestoneIndex":3542544,"status":"ended","questions":[{"answers":[{"value":1,"current":372250343375,"accumulated":30820033631800549},{"value":2,"current":74402847655,"accumulated":6414706069859334},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6"}}

**Comment by luca-yvr** [comment]
{
  "data": {
    "milestoneIndex": 3542544,
    "status": "ended",
    "questions": [
      {
        "answers": [
          {
            "value": 1,
            "current": 372250343375,
            "accumulated": 30820033631800548
          },
          {
            "value": 2,
            "current": 74402847655,
            "accumulated": 6414706069859334
          },
          {
            "value": 0,
            "current": 0,
            "accumulated": 0
          },
          {
            "value": 255,
            "current": 0,
            "accumulated": 0
          }
        ]
      }
    ],
    "checksum": "9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6"
  }
}

**Review by luca-yvr — APPROVED** [review]

**Review by the-real-rapete — APPROVED** [review]

**Review by plabbett — APPROVED** [review]
```json

"status":"ended",

"checksum":"9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6"

```

**Review by MaKla89 — APPROVED** [review]
approved

{"data":{"milestoneIndex":3542544,"status":"ended","questions":[{"answers":[{"value":1,"current":372250343375,"accumulated":30820033631800549},{"value":2,"current":74402847655,"accumulated":6414706069859334},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6"}}

**Review by coodos — APPROVED** [review]
"checksum": "9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6

**Comment by shufps** [comment]
All our Hornets give the same checksum :ok_hand:

**Review by shufps — APPROVED** [review]

**Comment by muXxer** [comment]
In case you wonder why the one balance sometimes has an of by one error, open it in another browser.
It's a JS rounding error in the browser because numbers are represented as floats.

**Review by timschloesser — APPROVED** [review]

**Review by renewid — APPROVED** [review]

**Review by nodemagnetron — APPROVED** [review]

**Review by JannemanDev — APPROVED** [review]
{"data":{"milestoneIndex":3542544,"status":"ended","questions":[{"answers":[{"value":1,"current":372250343375,"accumulated":30820033631800549},{"value":2,"current":74402847655,"accumulated":6414706069859334},{"value":0,"current":0,"accumulated":0},{"value":255,"current":0,"accumulated":0}]}],"checksum":"9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6"}}

**Review by WernerderChamp — APPROVED** [review]

**Review by TeeVeeEss — APPROVED** [review]
```json
 {
  "data": {
    "milestoneIndex": 3542544,
    "status": "ended",
    "questions": [
      {
        "answers": [
          {
            "value": 1,
            "current": 372250343375,
            "accumulated": 30820033631800548
          },
          {
            "value": 2,
            "current": 74402847655,
            "accumulated": 6414706069859334
          },
          {
            "value": 0,
            "current": 0,
            "accumulated": 0
          },
          {
            "value": 255,
            "current": 0,
            "accumulated": 0
          }
        ]
      }
    ],
    "checksum": "9d4079c427651060ce2d9bc2b6324725f1d7d6855d14357f6853809a96f84cd6"
  }
}
```

**Pull request merged**
