### PR TITLE
Verify "Assembly Staking Round 5" result

### PR DESCRIPTION
**Pull request by muXxer**
We want to verify the outcome of the `Assembly Round 5` staking event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

- Copy the following bash script into a file called `participation_get_result_assembly_05.sh`
```sh
#!/bin/bash
ADDR="https://YOUR-NODE-ADDRESS"
TOKEN="YOUR-JWT-TOKEN"

EVENT_ID="e4a155210e0bc125b489e4d49cdb82368e19682b29e7da9a6d4f2ca2a8bd25b9"
RESULT_FILE="assembly_05.json"

EVENT_STATUS="$( curl ${ADDR}/api/plugins/participation/events/${EVENT_ID}/status \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data.status' )"

grep -q 'ended' <<< "${EVENT_STATUS}" || { echo "ERROR: event has not ended yet"; exit 1 ; }

curl ${ADDR}/api/plugins/participation/admin/events/${EVENT_ID}/rewards \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data' > ${RESULT_FILE}

printf "Symbol:          %s\n" "$(jq '.symbol' ${RESULT_FILE})"
printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${RESULT_FILE})"
printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${RESULT_FILE})"
printf "Checksum:        %s\n" "$(jq '.checksum' ${RESULT_FILE})"
```
- Replace `ADDR` with the public REST API address of your HORNET node. 
- Replace `TOKEN` with your JWT Token. You can create a token using `./hornet tool jwt-api`.
- Save the file.
- Run `sudo apt update && sudo apt install curl jq`
- Run `chmod +x participation_get_result_assembly_05.sh`
- Run `./participation_get_result_assembly_05.sh`
- Copy the output of the script as a comment to this PR.
- Please press "Approve" if your checksum matches `6fb723510d954d55caffe78bed59de97fb572c044a2f5f8de67b97cc5d422bd4`. 
grafik

### CODE REVIEW

**Review by ockerocker — APPROVED** [review]

**Review by no8ody — APPROVED** [review]
Symbol: "microASMB"
Milestone index: 6420242
Total rewards: 995462732613081
Checksum: "6fb723510d954d55caffe78bed59de97fb572c044a2f5f8de67b97cc5d422bd4"

**Review by Danlino — APPROVED** [review]

**Comment by Danlino** [comment]
Symbol:          "microASMB"
Milestone index: 6420242
Total rewards:   995462732613081
Checksum:        "6fb723510d954d55caffe78bed59de97fb572c044a2f5f8de67b97cc5d422bd4"

**Review by Danlino — APPROVED** [review]
Symbol:          "microASMB"
Milestone index: 6420242
Total rewards:   995462732613081
Checksum:        "6fb723510d954d55caffe78bed59de97fb572c044a2f5f8de67b97cc5d422bd4"

**Review by the-real-ratpete — APPROVED** [review]

**Review by the-real-ratpete — APPROVED** [review]
2
Screenshot (12)

**Review by the-real-ratpete — APPROVED** [review]
Screenshot (11)

**Comment by JannemanDev** [comment]
IMG_1294

**Review by JannemanDev — APPROVED** [review]

**Review by shufps — APPROVED** [review]
Symbol:          "microASMB"
Milestone index: 6420242
Total rewards:   995462732613081
Checksum:        "6fb723510d954d55caffe78bed59de97fb572c044a2f5f8de67b97cc5d422bd4"

**Review by dlt-green — APPROVED** [review]
image

**Review by Travetown — APPROVED** [review]
Bildschirm­foto 2023-05-13 um 09 29 33

**Comment by Sn00pyoo7** [comment]
Unbenannt

**Review by Sn00pyoo7 — APPROVED** [review]

**Comment by 2g4y1** [comment]
Screenshot_20230513-113221

**Comment by 2g4y1** [comment]
Screenshot_20230513-113221

**Review by 2g4y1 — APPROVED** [review]

**Review by DrWoyzeck — APPROVED** [review]
image

**Review by mag-node — APPROVED** [review]
Assambly_5

**Review by gobbli — APPROVED** [review]
Address: iota-dach-news.dlt.green: (JWT-Token for API Access randomly generated)

─────────────────────────────────────────────────────────
Name: Assembly Round 5 Symbol: microASMB Status: ended

Event ID: e4a155210e0bc125b489e4d49cdb82368e19682b29e7da9a6d4f2ca2a8bd25b9
Checksum: 6fb723510d954d55caffe78bed59de97fb572c044a2f5f8de67b97cc5d422bd4

Milestone index: 6420242 Total rewards: 995462732613081
─────────────────────────────────────────────────────────

**Review by mogulbuster — COMMENTED** [review]
Screenshot 2023-05-15 at 23 23 11

**Review by Tombaaa — COMMENTED** [review]
image

**Review by 0xKtota — COMMENTED** [review]
Symbol: "microASMB"
Milestone index: 6420242

Total rewards: 995462732613081
Checksum: "6fb723510d954d55caffe78bed59de97fb572c044a2f5f8de67b97cc5d422bd4"

**Pull request merged**
