### PR TITLE
Verify "Shimmer Genesis Staking" result

### PR DESCRIPTION
**Pull request by muXxer**
We want to verify the outcome of the `Shimmer Genesis` staking event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

- Copy the following bash script into a file called `participation_get_result_shimmer.sh`
```sh
#!/bin/bash
ADDR="http://YOUR-NODE-ADDRESS:14265"
TOKEN="YOUR-JWT-TOKEN"

EVENT_ID="f6dbdad416e0470042d3fe429eb0e91683ba171279bce01be6d1d35a9909a981"
RESULT_FILE="shimmer.json"

EVENT_STATUS="$( curl ${ADDR}/api/plugins/participation/events/${EVENT_ID}/status \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data.status' )"

grep -q 'ended' <<< "${EVENT_STATUS}" || { echo "ERROR: event has not ended yet"; exit 1 ; }

curl ${ADDR}/api/plugins/participation/admin/events/${EVENT_ID}/rewards \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data' > ${RESULT_FILE}

printf "Symbol:          %s\n" "$(jq '.symbol' ${RESULT_FILE})"
printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${RESULT_FILE})"
printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${RESULT_FILE})"
printf "Checksum:        %s\n" "$(jq '.checksum' ${RESULT_FILE})"
```
- Replace `ADDR` with the public REST API address of your HORNET node. 
- Replace `TOKEN` with your JWT Token. You can create a token using `./hornet tool jwt-api`.
- Save the file.
- Run `sudo apt update && sudo apt install curl jq`
- Run `chmod +x participation_get_result_shimmer.sh`
- Run `./participation_get_result_shimmer.sh`
- Copy the output of the script as a comment to this PR.
- Please press "Approve" if your checksum matches `31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20`. 
grafik

### CODE REVIEW

**Review by alexsporn — APPROVED** [review]
Checked my Nodes

**Review by shufps — APPROVED** [review]
12 nodes checked :heavy_check_mark:

**Review by Snowli11 — APPROVED** [review]
# ./participation_get_result_shimmer.sh
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Comment by WernerderChamp** [comment]
Symbol: "SMR",
Milestone Index: 2879714,
Total Rewards: 1450896407249092,
Checksum: "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20",

**Review by Schnurzle — APPROVED** [review]
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Review by no8ody — APPROVED** [review]
Approved on 5 different nodes
```
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"
```

**Review by p00dl — APPROVED** [review]
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Review by dlt-green — APPROVED** [review]
Symbol: "SMR"
Milestone index: 2879714
Total rewards: 1450896407249092
Checksum: "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Comment by rohste** [comment]
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Review by rohste — APPROVED** [review]

**Comment by pauli2406** [comment]
Symbol: "SMR"
Milestone index: 2879714
Total rewards: 1450896407249092
Checksum: "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Review by pauli2406 — APPROVED** [review]

**Comment by luca-yvr** [comment]
root@chrysalis-1:/opt/hornet# ./participation_get_result_shimmer.sh
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Review by SiliconDroid — APPROVED** [review]
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Comment by jkl2e** [comment]
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Comment by kaktus2** [comment]
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Comment by Dr-Electron** [comment]
```
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"
```

**Review by Dr-Electron — APPROVED** [review]

**Comment by mrstormlars** [comment]
I'm not familiar enough with Linux to do the verification as described, but when I checked my nodes event details (from dashboard), I get the following results:
bilde

Clearly a mismatch between the total rewards compared to the others who have commented. I guess this is an error in the dashboard calculation, but thought I would comment on it nevertheless...

**Comment by alexsporn** [comment]
> Clearly a mismatch between the total rewards compared to the others who have commented. I guess this is an error in the dashboard calculation, but thought I would comment on it nevertheless...

See the discussion here https://github.com/iotaledger/participation-events/pull/3#issuecomment-1081052049

**Comment by Jch0141170** [comment]
I am not familiar with this tecnology, so I send you a screenshot. 
image

**Review by fr11 — COMMENTED** [review]
：)

**Review by the-real-rapete — COMMENTED** [review]
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Review by the-real-rapete — APPROVED** [review]
Symbol:          "SMR"
Milestone index: 2879714
Total rewards:   1450896407249092
Checksum:        "31cc1375782b0b4f3c6b45d1a014817facec364615ca8226a57ca3f9e12e7c20"

**Comment by harisyahot1** [comment]
ready for next step

**Pull request merged**
