### PR TITLE
Verify "Assembly Staking Round 1" result

### PR DESCRIPTION
**Pull request by muXxer**
We want to verify the outcome of the `Assembly Round 1` staking event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

- Copy the following bash script into a file called `participation_get_result_assembly_01.sh`
```sh
#!/bin/bash
ADDR="http://YOUR-NODE-ADDRESS:14265"
TOKEN="YOUR-JWT-TOKEN"

EVENT_ID="57607d9f8cefc366c3ead71f5b1d76cef1b36a07eb775158c541107951d4aecb"
RESULT_FILE="assembly_01.json"

EVENT_STATUS="$( curl ${ADDR}/api/plugins/participation/events/${EVENT_ID}/status \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data.status' )"

grep -q 'ended' <<< "${EVENT_STATUS}" || { echo "ERROR: event has not ended yet"; exit 1 ; }

curl ${ADDR}/api/plugins/participation/admin/events/${EVENT_ID}/rewards \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data' > ${RESULT_FILE}

printf "Symbol:          %s\n" "$(jq '.symbol' ${RESULT_FILE})"
printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${RESULT_FILE})"
printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${RESULT_FILE})"
printf "Checksum:        %s\n" "$(jq '.checksum' ${RESULT_FILE})"
```
- Replace `ADDR` with the public REST API address of your HORNET node. 
- Replace `TOKEN` with your JWT Token. You can create a token using `./hornet tool jwt-api`.
- Save the file.
- Run `sudo apt update && sudo apt install curl jq`
- Run `chmod +x participation_get_result_assembly_01.sh`
- Run `./participation_get_result_assembly_01.sh`
- Copy the output of the script as a comment to this PR.
- Please press "Approve" if your checksum matches `9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e`. 
grafik

### CODE REVIEW

**Review by shufps — APPROVED** [review]
12 nodes checked :heavy_check_mark:

**Review by alexsporn — APPROVED** [review]
Checked my Nodes

**Review by Snowli11 — APPROVED** [review]
# ./participation_get_result_assembly_01.sh
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Comment by Travetown** [comment]
Unfortunately I can't check it with the script at the moment.  The node itself shows me different numbers.
image

**Review by no8ody — APPROVED** [review]
Approved on 5 different nodes
```
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"
```

**Comment by alexsporn** [comment]
> Unfortunately I can't check it with the script at the moment. The node itself shows me different numbers.

Those numbers include staking addresses that did not get the minimum rewards required. You need to compare using the admin API endpoint.

**Comment by Travetown** [comment]
Which value is correct now?  The one displayed in the nodes or the value from the script?

**Comment by muXxer** [comment]
> Which value is correct now? The one displayed in the nodes or the value from the script?
The value in the script is the only valid one. The admin endpoint applies the filter, and only after that the correct result is printed.

**Comment by alexsporn** [comment]
> Which value is correct now? The one displayed in the nodes or the value from the script?

The one from the script that is taken directly from the node admin API. That endpoint filters out all adresses that did not accumulate the mininum rewards, so that is why the total number is smaller than in the "status" endpoint the dashboard or thetangle shows.

**Review by p00dl — APPROVED** [review]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Comment by dlt-green** [comment]
root@www:/var/www/html# bash participation_get_result_assembly_01.sh
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Review by dlt-green — APPROVED** [review]
Symbol: "microASMB"
Milestone index: 2879714
Total rewards: 5805198310256865
Checksum: "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Review by baylander — APPROVED** [review]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Comment by luca-yvr** [comment]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Review by SiliconDroid — APPROVED** [review]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Comment by WernerderChamp** [comment]
Symbol: "microASMB"
Milestone index: 2879714
Total rewards: 5805198310256865
Checksum: "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Comment by jkl2e** [comment]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Comment by Dr-Electron** [comment]
```
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"
```

**Review by Dr-Electron — APPROVED** [review]

**Comment by kaktus2** [comment]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Review by kaktus2 — APPROVED** [review]

**Review by the-real-rapete — COMMENTED** [review]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Review by the-real-rapete — APPROVED** [review]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Review by DerBanane — APPROVED** [review]

**Comment by Sn00pyoo7** [comment]
Symbol:          "microASMB"
Milestone index: 2879714
Total rewards:   5805198310256865
Checksum:        "9314154fa763ad84b7c289314f3c9a10f2b02a659b15ebb41bcc0c1a6e82aa3e"

**Review by Sn00pyoo7 — APPROVED** [review]

**Comment by muXxer** [comment]
The results have been successfully verified!
A big thank you to everyone involved in this process! :+1:

**Comment by hackicodi** [comment]
Hello, how to create the jwt token? ./hornet tool jwt-api doesn't work

**Pull request merged**
