### PR TITLE
Verify "Assembly Staking Round 2" result

### PR DESCRIPTION
**Pull request by muXxer**
We want to verify the outcome of the `Assembly Round 2` staking event.

To do this, we need the help of our community node operators who tracked this event.

Please follow the next steps:

- Copy the following bash script into a file called `participation_get_result_assembly_02.sh`
```sh
#!/bin/bash
ADDR="http://YOUR-NODE-ADDRESS:14265"
TOKEN="YOUR-JWT-TOKEN"

EVENT_ID="90ab02d8f700fcb3b31ff577416ecb105697a664738bec45b626920337a280e0"
RESULT_FILE="assembly_02.json"

EVENT_STATUS="$( curl ${ADDR}/api/plugins/participation/events/${EVENT_ID}/status \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data.status' )"

grep -q 'ended' <<< "${EVENT_STATUS}" || { echo "ERROR: event has not ended yet"; exit 1 ; }

curl ${ADDR}/api/plugins/participation/admin/events/${EVENT_ID}/rewards \
  --http1.1 \
  -s \
  -X GET \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer ${TOKEN}" | jq '.data' > ${RESULT_FILE}

printf "Symbol:          %s\n" "$(jq '.symbol' ${RESULT_FILE})"
printf "Milestone index: %s\n" "$(jq '.milestoneIndex' ${RESULT_FILE})"
printf "Total rewards:   %s\n" "$(jq '.totalRewards' ${RESULT_FILE})"
printf "Checksum:        %s\n" "$(jq '.checksum' ${RESULT_FILE})"
```
- Replace `ADDR` with the public REST API address of your HORNET node. 
- Replace `TOKEN` with your JWT Token. You can create a token using `./hornet tool jwt-api`.
- Save the file.
- Run `sudo apt update && sudo apt install curl jq`
- Run `chmod +x participation_get_result_assembly_02.sh`
- Run `./participation_get_result_assembly_02.sh`
- Copy the output of the script as a comment to this PR.
- Please press "Approve" if your checksum matches `b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5`. 
grafik

### CODE REVIEW

**Comment by alexsporn** [comment]
```
Symbol:          "microASMB"
Milestone index: 3871289
Total rewards:   2387828122797240
Checksum:        "b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5"
```

**Review by alexsporn — APPROVED** [review]

**Review by shufps — APPROVED** [review]
```
Symbol:          "microASMB"
Milestone index: 3871289
Total rewards:   2387828122797240
Checksum:        "b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5"
```
same result on all of our API-hornets :rocket:

**Review by dlt-green — APPROVED** [review]
asmb02

**Review by no8ody — APPROVED** [review]
```Symbol: "microASMB"
Milestone index: 3871289
Total rewards: 2387828122797240
Checksum: "b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5"```

**Review by ockerocker — APPROVED** [review]
Bildschirmfoto vom 2022-07-21 16-49-25

**Review by p00dl — APPROVED** [review]
image


  "symbol": "microASMB",
  "milestoneIndex": 3871289,
  "totalRewards": 2387828122797240,
  "checksum": "b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5",

**Comment by DrWoyzeck** [comment]
Approve_Assembly_round2

**Comment by fhb191309** [comment]
```console
Symbol: "microASMB"
Milestone index: 3871289
Total rewards: 2387828122797240
Checksum: "b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5"
```

**Review by gobbli — APPROVED** [review]
Event ID:: 90ab02d8f700fcb3b31ff577416ecb105697a664738bec45b626920337a280e0
 Symbol: microASMB
 Milestone index: 3871289                                       
 Total rewards:	 2387828122797240                              
 Checksum: b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5

**Review by zKtota — APPROVED** [review]
Symbol: "microASMB" 
Milestone index: 3871289   
Total rewards: 2387828122797240 
Checksum: "b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5"

**Comment by mogulbuster** [comment]
Screenshot 2022-07-21 at 19 02 03

**Comment by Sn00pyoo7** [comment]
Symbol:          "microASMB"
Milestone index: 3871289
Total rewards:   2387828122797240
Checksum:        "b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5"

**Review by Sn00pyoo7 — APPROVED** [review]

**Comment by Arion941** [comment]
Symbol:          "microASMB"
Milestone index: 3871289
Total rewards:   2387828122797240
Checksum:        "b30f0588303ff2a48c950f8f79e6a9ae3eeb833f36bf261a0e2bf19ade4afed5"

**Pull request merged**
